name: aggregamus
description: LEL

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dsbuntis: ^4.0.0-alpha.2
  schttp: ^2.0.0

dependency_overrides:
  dsbuntis:
    git:
      url: https://github.com/Ampless/dsbuntis.git

dev_dependencies:
  pedantic: ^1.11.0
