name: aggregamus
description: A Big Data project based on dsbuntis
version: 1.0.0
repository: https://github.com/Ampless/aggregamus

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dsbuntis: ^8.0.0
  prometheus_client: ^1.0.0
  prometheus_client_shelf: ^1.0.0
  schttp: ^4.1.0
  shelf: ^1.4.0

dev_dependencies:
  lints: ^1.0.1
